title: DuiNaru
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  개발과 경험을 담는 블로그
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://duinaru.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  DuiNaru

# Polyglot setting
languages: ['ko', 'ja', 'en']
default_lang: 'ko'
exclude_from_localization: ['images']
parallel_localization: false

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # multilanguage icons
  - scope:
      path: "assets/images/lang"
    values:
      lang_img: true

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-polyglot
 # - jekyll-multiple-languages-plugin

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _site
  - deploy.ps1
  - Gemfile
